version: '3'
volumes: 
  data:
networks:
  network_db:
  network_app:
  network_queue:
services:
  db:
    image: postgres
    environment:
      # Bank access without authentication
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data:/var/lib/postgresql/data
      # Scripts run at container startup
      - ./db:/scripts
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - network_db
  app:
    image: nginx:1.13
    # Site
    volumes: 
      - ./app/html:/usr/share/nginx/html/
      # Reverse proxy configuration
      - ./app/proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - network_app
    depends_on: 
      - API
  api:
    image: python:3.6
    volumes: 
      - ./api:/api
    working_dir: /api
    command: bash ./api.sh
    networks: 
      - network_db
      - network_app
      - network_queue
    depends_on: 
      - .db
      - Queue
  queue:
    image: redis:3.2
    networks: 
      - network_queue
  server_email:
    build: server_email
    volumes: 
      - ./server_email:/server_email
    working_dir: /server_email
    Command: server_email.py
    networks: 
      - network_queue
    depends_on: 
      - Queue

